---
- name: Parse and schedule job from input
  hosts: localhost
  vars:
    input_string: "LXP-RHE-QTR-02SAT-0800-TS"
    day_mapping:
      MON: 0
      TUE: 1
      WED: 2
      THU: 3
      FRI: 4
      SAT: 5
      SUN: 6
  tasks:
    - name: Debug input string
      debug:
        msg: "Input string: {{ input_string }}"

    - name: Extract relevant data from the input string
      set_fact:
        quarter: "{{ (input_string | regex_search('QTR-\\d', '\\0') | regex_replace('QTR-', ''))[0] }}"
        day_of_week_str: "{{ (input_string | regex_search('(MON|TUE|WED|THU|FRI|SAT|SUN)', '\\1'))[0] }}"
        time: "{{ (input_string | regex_search('\\d{4}', '\\0'))[0] }}"

    - name: Debug extracted values
      debug:
        msg: |
          Extracted values:
          Quarter: {{ quarter }}
          Day of Week (raw): {{ day_of_week_str }}
          Time: {{ time }}

    - name: Validate extracted data
      fail:
        msg: "Failed to extract all required information from input_string. Extracted: quarter={{ quarter }}, day_of_week_str={{ day_of_week_str }}, time={{ time }}"
      when: quarter == '' or day_of_week_str == '' or time == ''

    - name: Map day_of_week_str to Python weekday
      set_fact:
        day_of_week: "{{ day_mapping[day_of_week_str | upper()] }}"

    - name: Debug the mapped day_of_week
      debug:
        msg: "Day of week '{{ day_of_week_str }}' maps to Python weekday '{{ day_of_week }}'"

    - name: Calculate the start of the quarter
      set_fact:
        quarter_start_month: "{{ (quarter | int - 1) * 3 + 1 }}"
        current_year: "{{ ansible_date_time.year }}"

    - name: Calculate the first matching day of the quarter
      set_fact:
        target_date: >-
          {{
            ((current_year ~ '-' ~ quarter_start_month ~ '-01') | to_datetime('%Y-%m-%d')
            + timedelta(days=(day_of_week - (current_year ~ '-' ~ quarter_start_month ~ '-01') | to_datetime('%Y-%m-%d').weekday()) % 7))
            .strftime('%Y-%m-%dT') ~ (time[:2] ~ ':' ~ time[2:] ~ ':00Z')
          }}

    - name: Debug the calculated target date
      debug:
        msg: "The job is scheduled to run on {{ target_date }}"
