---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        endpoint: /endpoint
  ## Define the conditions we are looking for
  rules:
    - name: Increase Storage
      condition: event.payload.message == "increase storage"
  ## Define the action we should take should the condition be met
      action:
        run_job_template:
          name: "Test Application"
          organization: Default
          job_args: 
            extra_vars: "{{ event.payload }}"

    - name: Capture and Log Message
      condition: event.payload is defined
      actions:
        - debug:
            msg: "Received message: {{ event.payload }}"

    - name: Always Runs
      condition: True
      actions:
        - debug:
            msg: "You will always see me {{ event.payload }}"

## Here is the bash script that is run from the host:
#
##!/bin/bash
#
## Get the server's hostname using 
## AWS's Instance Metadata service static IP address 169.254.169.254
#target_host=$(curl -s http://169.254.169.254/latest/meta-data/public-hostname)
#
## Set the message variable
#message="increase storage"
#
## Execute the curl command with the variables
#curl -v -k -H 'Content-Type: application/json' -d "{\"message\": \"$message\", \"target_host\": \"$target_host\"}" <eda controller fqdn>:5000/endpoint