---
- name: Listen for incidents on a webhook from ServiceNow
  hosts: all
  sources:
    - name: Listen for incidents from ServiceNow
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5289

  rules:
    - name: Increase CPU on requested Node
      condition: event.payload.subcategory == "cpu"
      action:
        run_workflow_template:
          name: "mbredeme - Automated Response High CPU Service Now Incident"
          organization: "Infrastructure"
          job_args: 
            extra_vars: 
              vm_name: "{{ event.payload.u_vm_name }}"
              ticket_number: "{{ event.payload.number }}"
              comment: "Ansible Increasing CPU by core"
              snow_incident_link: "<placeholder for snow_incident_link> {{ event.payload.number }}"
              payload: "{{ event.payload }}"

