---
- name: Listen for incidents on a webhook from ServiceNow
  hosts: all
  sources:
    - name: Listen for incidents from ServiceNow
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5289

  rules:
    - name: Output Snow Meta Information
      condition: event.payload.subcategory == "cpu"
      action:
        debug: 
          var: event.payload

#    - name: show subscategory
#      condition: True
#      action:
#        debug: 
#          msg: "Subcategory is {{ event.payload.subcategory }}"
#
#    - name: Increase CPU on requested Node
#      condition: event.payload.subcategory == "cpu"
#      action:
#        run_job_template:
#          name: "Increase VM CPU"
#          organization: Infrastructure
#          job_args: 
#            extra_vars: 
#              vm_name: "{{ event.payload.u_vm_name }}"
#              payload: "{{ event.payload }}"