---
- name: check webserver
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - https://datadog.shadowman.dev
        delay: 10
  
  rules:
    - name: Run Job
      condition: event.url_check.status == "down"
      action: 
        run_job_template:
          name: "mkbredem - Create a ServiceNow Ticket on Security Incident"
          organization: "Infrastructure"
          extra_vars:
            description: "{{ event.meta.url_check }}"